import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Suscribe from "@/Components/suscribe";
import Component2 from "@/Components/component2";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section id="c1" style={{ backgroundColor: "#f4e6e9" }}>
        <Suscribe />
      </section>
      <section id="c2" style={{ backgroundColor: "#FDF7F8" }}>
        <Component2 />
      </section>
    </>
  );
}
